-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for International Patient Journey Analytics
-- ============================================================================
USE DATABASE PATIENT_JOURNEY;
USE SCHEMA ML;

-- ML.FORECAST: PATIENT_DEMAND_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.PATIENT_DEMAND_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.SOURCE_MARKET_TRENDS'),
  SERIES_COLNAME => 'SOURCE_COUNTRY',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.PATIENT_DEMAND_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.PATIENT_DEMAND_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: CONVERSION_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.CONVERSION_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CONVERSION_FUNNEL'),
  SERIES_COLNAME => 'SOURCE_TREATMENT',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.CONVERSION_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.CONVERSION_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CONVERSION_FUNNEL'), SERIES_COLNAME => 'SOURCE_TREATMENT', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

