-- ============================================================================
-- 99_RESET.SQL — Reset International Patient Journey Analytics to clean demo state
-- ============================================================================
USE DATABASE PATIENT_JOURNEY;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_GENERATE_RECOMMENDATIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SEND_FOLLOWUPS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PATIENT_LIFETIME_VALUE REFRESH;
ALTER DYNAMIC TABLE CURATED.CONVERSION_FUNNEL REFRESH;
ALTER DYNAMIC TABLE CURATED.PACKAGE_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.SOURCE_MARKET_TRENDS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PATIENT_JOURNEY.RAW.PATIENTS → 45000
-- SELECT COUNT(*) FROM PATIENT_JOURNEY.RAW.INQUIRIES → 120000
-- SELECT COUNT(*) FROM PATIENT_JOURNEY.CURATED.CONVERSION_FUNNEL WHERE CONVERSION_RATE < 0.15 → >5

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS RESUME;
ALTER TASK IF EXISTS APP.TASK_SEND_FOLLOWUPS RESUME;
ALTER TASK IF EXISTS APP.TASK_GENERATE_RECOMMENDATIONS RESUME;
